In [1]:
import numpy as np

### 5. Operation

In [3]:
a = np.arange(1, 11, dtype=np.float32)
a.sum()

55.0

In [4]:
b = np.arange(1, 13).reshape(3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
b.sum()

78

In [6]:
# 세로 방향의 합
b.sum(axis = 0)

array([15, 18, 21, 24])

In [7]:
# 가로 방향의 합
b.sum(axis = 1)

array([10, 26, 42])

In [8]:
# 평균
b.mean(axis = 0), b.mean(axis = 1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

In [9]:
# 표준편차
b.std(axis = 0), b.std(axis = 1)

(array([3.26598632, 3.26598632, 3.26598632, 3.26598632]),
 array([1.11803399, 1.11803399, 1.11803399]))

In [12]:
# 수학 함수
x = np.arange(-1., 1.01, 0.01)
x.size

201

In [48]:
# sigmoid 함수
y = 1./(1. + np.exp(-x))

- Concatenate

In [15]:
a = np.arange(1, 5).reshape(2, 2)
b = np.array([[5, 6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# 전치행렬(Transpose)
b.T

array([[5],
       [6]])

In [18]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [19]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

### 6. Array operation

In [20]:
# element-wise operation
a + a

array([[2, 4],
       [6, 8]])

In [21]:
a - a

array([[0, 0],
       [0, 0]])

In [22]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [23]:
a / a

array([[1., 1.],
       [1., 1.]])

- dot product

In [25]:
a = np.arange(1, 7).reshape(2, 3)
a.dot(a.T)

array([[14, 32],
       [32, 77]])

In [26]:
np.dot(a, a.T)

array([[14, 32],
       [32, 77]])

- Broadcasting

In [28]:
a + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [30]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [33]:
a + np.array([10, 20, 30])   # shape이 비슷해야함. 

array([[11, 22, 33],
       [14, 25, 36]])

### 7. Comparison

In [35]:
a = np.arange(5)   # 0, 1, 2, 3, 4
np.all(a), np.any(a)   # np.all(a) : 모두 True인가, np.any(a) : True가 하나라도 있는가

(False, True)

In [37]:
a > 2

array([False, False, False,  True,  True])

In [38]:
a[a>2]   # True인 요소 출력

array([3, 4])

- Logical operation

In [39]:
a = np.arange(5)
b = np.logical_and(a>0, a<3)
b

array([False,  True,  True, False, False])

In [41]:
c =np.logical_not(b)
c

array([ True, False, False,  True,  True])

In [42]:
np.logical_or(b, c)

array([ True,  True,  True,  True,  True])

In [43]:
np.logical_xor(b,c)

array([ True,  True,  True,  True,  True])

In [44]:
a = np.arange(5)
np.where(a>2)   # a>2 인 인데스값 출력

(array([3, 4], dtype=int64),)

- NaN(Not a Number), Inf(Infinite)

In [45]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [47]:
np.isnan(a), np.isfinite(a)  #  

(array([False,  True, False]), array([ True, False, False]))

- argmax, argmin

In [50]:
a = np.arange(6)   # 0, 1, 2, 3, 4, 5
np.argmax(a), np.argmin(a)

(5, 0)

In [51]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
np.argmax(b, axis = 0)

array([2, 2, 2, 2], dtype=int64)

In [53]:
np.argmin(b, axis = 1)

array([0, 0, 0], dtype=int64)