In [1]:
import numpy as np

### 8. boolean and Index

In [6]:
np.random.seed(2021)
a =np.random.uniform(1, 10, 4)
a

array([6.45380451, 7.60032425, 2.25052441, 3.81405775])

In [9]:
a > 3

array([ True,  True, False,  True])

In [11]:
# Boolean Indexing
# 값이 3을 초과하는 엘리먼트만 가져옴
a[a>3]

array([6.45380451, 7.60032425, 3.81405775])

- Fancy index

In [13]:
a = np.arange(1, 5) * 2
a

array([2, 4, 6, 8])

In [16]:
b = np.array([0, 1, 3, 2, 1, 3])
a[b]

array([2, 4, 8, 6, 4, 8])

In [22]:
a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
a = np.arange(8).reshape(2, 4)
b = np.array([0, 0, 1, 1, 0])
c = np.array([0, 2, 3, 1, 2])
a[b,c]

array([0, 2, 7, 5, 2])