In [2]:
import numpy as np

1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.

10 20 30 40

50 60 70 80

In [14]:
a = np.arange(10, 90, 10).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2. 다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0, 1, 2, 3, 4],

              [ 5, 6, 7, 8, 9],
              
              [10, 11, 12, 13, 14]])
              
 1) 이 행렬에서 값 7 을 인덱싱한다.

In [49]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
m[1,2]

7

2) 이 행렬에서 값 14 을 인덱싱한다.

In [18]:
m[2,4]

14

3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

In [19]:
m[1:2,1:3]

array([[6, 7]])

4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [22]:
m[1:3,2:3]

array([[ 7],
       [12]])

5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.


In [23]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.

 1) 이 배열에서 3의 배수를 찾아라.


In [54]:
m.shape(15, )

TypeError: 'tuple' object is not callable

In [31]:
m[m%3==0]

array([ 0,  3,  6,  9, 12])

In [ ]:
2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

In [32]:
m[m%4==1]

array([ 1,  5,  9, 13])

In [ ]:
3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [39]:
m[(m%3==0) & (m%4==1)]

array([9])

4. 값을 직접 입력하지 말고
우측의 행렬을 만드시오.

2, 1, 0, 0, 0

3, 2, 1, 0, 0

0, 3, 2, 1, 0

0, 0, 3, 2, 1

0, 0, 0, 3, 2

5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.

 1) 전체의 최댓값

In [ ]:
2) 각 행의 합

In [ ]:
3) 각 행의 최댓값

In [ ]:
4) 각 열의 평균

In [ ]:
5) 각 열의 최솟값

In [ ]:
6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.
array([[ 1, 2, 3, 4],
       [ 46, 99, 100, 71],
       [ 81, 59, 90, 100]])


In [ ]:
7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.

In [ ]:
8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.