In [1]:
import numpy as np

1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.

10 20 30 40

50 60 70 80

In [2]:
a = np.arange(10, 90, 10).reshape(2,4)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2. 다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0, 1, 2, 3, 4],

              [ 5, 6, 7, 8, 9],
              
              [10, 11, 12, 13, 14]])
              
 1) 이 행렬에서 값 7 을 인덱싱한다.

In [3]:
m = np.arange(15).reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
m[1,2]

7

2) 이 행렬에서 값 14 을 인덱싱한다.

In [5]:
m[2,4]

14

3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

In [6]:
m[1:2,1:3]

array([[6, 7]])

4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [7]:
m[1:3,2:3]

array([[ 7],
       [12]])

5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.


In [8]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.

 1) 이 배열에서 3의 배수를 찾아라.


In [9]:
f=m.reshape(15,)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
f[f%3==0]

array([ 0,  3,  6,  9, 12])

2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

In [11]:
f[f%4==1]

array([ 1,  5,  9, 13])

3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [12]:
f[(f%3==0) & (f%4==1)]

array([9])

4. 값을 직접 입력하지 말고
우측의 행렬을 만드시오.

2, 1, 0, 0, 0

3, 2, 1, 0, 0

0, 3, 2, 1, 0

0, 0, 3, 2, 1

0, 0, 0, 3, 2

In [13]:
np.eye(5, 5, -1)*3 + np.eye(5, 5, 0)*2 + np.eye(5, 5, 1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.

 1) 전체의 최댓값

In [14]:
np.random.seed(2021)
a = np.random.uniform(0, 10, 30).reshape(5, 6)
a

array([[6.05978279, 7.33369361, 1.38947157, 3.12673084, 9.97243281,
        1.28162375],
       [1.78993106, 7.52925429, 6.62160514, 7.84310132, 0.96894396,
        0.58571285],
       [9.6239599 , 6.16557444, 0.86629961, 5.61272363, 6.16524709,
        9.63843023],
       [5.74304294, 3.71160848, 4.52145244, 2.01850248, 5.69305118,
        1.95095974],
       [5.83704016, 4.76313474, 5.178144  , 8.23098634, 7.32225027,
        0.69056275]])

In [15]:
a.max()

9.972432813403188

2) 각 행의 합

In [16]:
a.sum(axis = 1)

array([29.16373537, 25.33854862, 38.07223489, 23.63861727, 32.02211826])

3) 각 행의 최댓값

In [17]:
a.max(axis = 1)

array([9.97243281, 7.84310132, 9.63843023, 5.74304294, 8.23098634])

4) 각 열의 평균

In [18]:
a.mean(axis = 0)

array([5.81075137, 5.90065311, 3.71539455, 5.36640892, 6.02438506,
       2.82945787])

5) 각 열의 최솟값

In [19]:
a.min(axis = 0)

array([1.78993106, 3.71160848, 0.86629961, 2.01850248, 0.96894396,
       0.58571285])

6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

array([[ 1, 2, 3, 4],

       [ 46, 99, 100, 71],
       
       [ 81, 59, 90, 100]])


In [20]:
b = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
b

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [21]:
b.argsort()

array([[0, 1, 2, 3],
       [0, 3, 1, 2],
       [1, 0, 2, 3]], dtype=int64)

7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.

In [22]:
python = np.random.randint(1, 6, 100)
python

array([3, 3, 1, 3, 5, 4, 4, 2, 2, 2, 3, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4, 4,
       4, 4, 3, 2, 4, 3, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3, 3, 3, 4,
       5, 2, 2, 1, 1, 5, 2, 4, 5, 1, 4, 2, 4, 2, 4, 2, 2, 4, 4, 2, 4, 2,
       1, 2, 3, 1, 4, 1, 1, 2, 4, 5, 4, 5, 2, 5, 2, 2, 5, 2, 3, 5, 4, 2,
       3, 4, 3, 1, 1, 5, 4, 2, 4, 5, 5, 5])

In [23]:
python.mean()

3.15

8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.