In [1]:
import numpy as np
import pandas as pd

### 연습 문제 4.1.1
### 1. 임의로 두 개의 시리즈 객체를 만든다. 모두 문자열 인덱스를 가져야 하며 두 시리즈에 공통적으로 포함되지 않는 라벨이 있어야 한다.

In [2]:
a = pd.Series([90, 80, 70, 60],
              index=["A", "B", "C", "D"])
b = pd.Series([10, 20, 30, 40],
              index=["E", "F", "G", "H"])
a, b

(A    90
 B    80
 C    70
 D    60
 dtype: int64,
 E    10
 F    20
 G    30
 H    40
 dtype: int64)

### 2. 위에서 만든 두 시리즈 객체를 이용하여 사칙 연산을 한다.

In [3]:
a.values + b.values

array([100, 100, 100, 100], dtype=int64)

In [4]:
a.values - b.values

array([80, 60, 40, 20], dtype=int64)

In [5]:
a.values * b.values

array([ 900, 1600, 2100, 2400], dtype=int64)

In [6]:
a.values / b.values

array([9.        , 4.        , 2.33333333, 1.5       ])

### 연습 문제 4.1.2
### 3. 다음 조건을 만족하는 임의의 데이터프레임을 하나 만든다.

(1) 열의 갯수와 행의 갯수가 각각 5개 이상이어야 한다.

(2) 열에는 정수, 문자열, 실수 자료형 데이터가 각각 1개 이상씩 포함되어 있어야 한다.

In [7]:
data = {
    "a": ["수도권", 1, 2, 3.1234],
    "b": ["충청도", 1, 2, 3.1234],
    "c": ["강원도", 1, 2, 3.1234],
    "d": ["전라도", 1, 2, 3.1234],
    "e": ["경상도", 1, 2, 3.1234],
}
df = pd.DataFrame(data)
df

a       b       c       d       e
0     수도권     충청도     강원도     전라도     경상도
1       1       1       1       1       1
2       2       2       2       2       2
3  3.1234  3.1234  3.1234  3.1234  3.1234

### 연습 문제 4.1.3
### 4. 다음 데이터프레임에서 지정하는 데이터를 뽑아내거나 처리하라.

In [8]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

(1) 모든 학생의 수학 점수를 시리즈로 나타낸다.

In [9]:
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

(2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.

In [10]:
df[['국어', '영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

(3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.

In [11]:
df["평균"] = (((df['국어'] + df['영어']) + df['수학']) / 3)
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  40  70  46.666667

(4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.

In [12]:
df.loc['방자', '영어'] = 80
df["평균"] = (((df['국어'] + df['영어']) + df['수학']) / 3)
df

국어  영어  수학         평균
춘향  80  90  90  86.666667
몽룡  90  70  60  73.333333
향단  70  60  80  70.000000
방자  30  80  70  60.000000

(5) 춘향의 점수를 데이터프레임으로 나타낸다.

In [13]:
df[:1]

국어  영어  수학         평균
춘향  80  90  90  86.666667

(6) 향단의 점수를 시리즈로 나타낸다.

In [14]:
df.loc['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

### 연습 문제 4.3.1
### 5. 
(1) 모든 행과 열에 라벨을 가지는 5 x 5 이상의 크기를 가지는 데이터프레임을 만든다.

In [15]:
df = pd.DataFrame(np.arange(0, 25).reshape(5,5),
                  index=["a", "b", "c", "d", "e"],
                  columns=["A", "B", "C", "D", "E"])
df

A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24

(2) 10가지 이상의 방법으로 특정한 행과 열을 선택한다.

In [16]:
df["A"]

a     0
b     5
c    10
d    15
e    20
Name: A, dtype: int32

In [17]:
df.A

a     0
b     5
c    10
d    15
e    20
Name: A, dtype: int32

In [18]:
df[["A"]]

A
a   0
b   5
c  10
d  15
e  20

In [19]:
df[["A", "C"]]

A   C
a   0   2
b   5   7
c  10  12
d  15  17
e  20  22

In [20]:
df[:1]

A  B  C  D  E
a  0  1  2  3  4

In [21]:
df[0:2]

A  B  C  D  E
a  0  1  2  3  4
b  5  6  7  8  9

In [22]:
df["a":"b"]

A  B  C  D  E
a  0  1  2  3  4
b  5  6  7  8  9

### 연습 문제 4.4.1
### 6. 타이타닉호 승객 데이터의 데이터 개수를 각 열마다 구해본다.

In [23]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [24]:
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

### 연습 문제 4.4.2
### 7. sort_values 메서드를 사용하여 타이타닉호 승객에 대해 성별(sex) 인원수, 나이별(age) 인원수, 선실별(class) 인원수, 사망/생존(alive) 인원수를 구하라.

### 연습 문제 4.4.3
### 8.
(1) 타이타닉호 승객의 평균 나이를 구하라.

In [25]:
titanic['age'].mean()

29.69911764705882

(2) 타이타닉호 승객중 여성 승객의 평균 나이를 구하라.

In [27]:
titanic_f = titanic.loc[titanic['sex']=='female']
titanic_f['age'].mean()

27.915708812260537

(3) 타이타닉호 승객중 1등실 선실의 여성 승객의 평균 나이를 구하라.

In [28]:
titanic_F = titanic_f.loc[titanic_f['class']=='First']
titanic_F['age'].mean()

34.61176470588235

### 연습 문제 4.4.4
### 9. 타이타닉호의 승객에 대해 나이와 성별에 의한 카테고리 열인 category1 열을 만들어라. category1 카테고리는 다음과 같이 정의된다.

20살이 넘으면 성별을 그대로 사용한다.

20살 미만이면 성별에 관계없이 “child”라고 한다.


In [29]:
titanic["category1"] = titanic.apply(lambda r: r.sex if r.age >= 20 else "child", axis=1)
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone category1  
0    man        True  NaN  Southampton    no  False      male  
1  woman       False    C    Cherbourg   yes  False    female  
2  woman       False  NaN  Southampton   yes   True    female  
3  woman       False    C  Southampton   yes  False    female  
4    man        True  NaN  Southampton    no   True      male

### 연습 문제 4.4.5
### 10. 타이타닉호의 승객 중 나이를 명시하지 않은 고객은 나이를 명시한 고객의 평균 나이 값이 되도록 titanic 데이터프레임을 고쳐라.

### 연습 문제 4.4.6
### 11. 타이타닉호의 승객에 대해 나이와 성별에 의한 카테고리 열인 category2 열을 만들어라. category2 카테고리는 다음과 같이 정의된다.

성별을 나타내는 문자열 male 또는 female로 시작한다.

성별을 나타내는 문자열 뒤에 나이를 나타내는 문자열이 온다.

예를 들어 27살 남성은 male27 값이 된다.

### 연습 문제 4.4.7
### 12. 타이타닉호 승객을 ‘미성년자’, ‘청년’, ‘중년’, ‘장년’, ‘노년’ 나이 그룹으로 나눈다.

bins = [1, 20, 30, 50, 70, 100]
labels = ["미성년자", "청년", "중년", "장년", "노년"]
그리고 각 나이 그룹의 승객 비율을 구한다. 비율의 전체 합은 1이 되어야 한다.

### 연습 문제 4.4.8
### 13. 타이타닉호의 승객에 대해 나이와 성별에 의한 카테고리 열인 category3 열을 만들어라. category3 카테고리는 다음과 같이 정의된다.

20살 미만이면 성별에 관계없이 “미성년자”라고 한다.

20살 이상이면 나이에 따라 “청년”, “중년”, “장년”, “노년”을 구분하고 그 뒤에 성별을 나타내는 “남성”, “여성”을 붙인다.

### 연습 문제 4.5.1
### 14. 5명의 학생의 국어, 영어, 수학 점수를 나타내는 데이터프레임을 다음과 같이 만든다.

(1) 학생 이름을 나타내는 열을 포함시키지 않고 데이터프레임 df_score1 을 생성한 후, df_score1.index 속성에 학생 이름을 나타내는 열을 지정하여 인덱스를 지정한다. reset_index 명령으로 이 인덱스 열을 명령으로 일반 데이터열로 바꾸여 데이터프레임 df_score2을 만든다.

(2) 학생 이름을 나타내는 열이 일반 데이터 열을 포함하는 데이터프레임 df_score2에 set_index 명령을 적용하여 다시 학생 이름을 나타내는 열을 인덱스로 변경한다.

### 연습 문제 4.5.2
### 15. A 반 학생 5명과 B반 학생 5명의 국어, 영어, 수학 점수를 나타내는 데이터프레임을 다음과 같이 만든다.
(1) “반”, “번호”, “국어”, “영어”, “수학” 을 열로 가지는 데이터프레임 df_score3을 만든다.

In [31]:
data = {
    "반": ["A", "A", "A", "A", "A", "B", "B", "B", "B", "B"],
    "번호": [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
    "국어": [70, 80, 90, 100, 60, 50, 70, 80, 90, 90],
    "영어": [80, 90, 70, 60, 50, 40, 50, 80, 90, 70],
    "수학": [70, 80, 90, 80, 70, 50, 90, 90, 80, 70]
}
df_score3 = pd.DataFrame(data)
df_score3

반  번호   국어  영어  수학
0  A   1   70  80  70
1  A   2   80  90  80
2  A   3   90  70  90
3  A   4  100  60  80
4  A   5   60  50  70
5  B   1   50  40  50
6  B   2   70  50  90
7  B   3   80  80  90
8  B   4   90  90  80
9  B   5   90  70  70

(2) df_score3을 변형하여 1차 행 인덱스로 “반”을 2차 행 인덱스로 “번호”을 가지는 데이터프레임 df_score4을 만든다.

In [32]:
df_score3.index.names = ["반", "번호"]

ValueError: Length of new names must be 1, got 2

(3) 데이터 프레임 df_score4에 각 학생의 평균을 나타내는 행을 오른쪽에 추가한다.

(4) df_score3을 변형하여 행 인덱스로 “번호”를, 1차 열 인덱스로 “국어”, “영어”, “수학”을, 2차 열 인덱스로 “반”을 가지는 데이터프레임 df_score5을 만든다.

(5) 데이터 프레임 df_score5에 각 반별 각 과목의 평균을 나타내는 행을 아래에 추가한다.